version: 2
jobs:
  setup:
    working_directory: ~/circleci-test
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: setup venv
          command: |
            python3 -m venv root
      - run:
          name: install dependancies
          command: |
            . ./root/bin/activate
            pip install -r requirements.txt

      - run:
          name: run tests
          command: |
            . ./root/bin/activate
            pytest ~/circleci-test/common/utils.py
workflows:
  version: 2
  build_test:
    jobs:
      - setup
