version: 2
jobs:
  setup:
    working_directory: ~/circleci-test
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: setup venv
          command: |
            python3 -m venv root
      - run:
          name: install dependancies
          command: |
            . ./root/bin/activate
            pip install -r ./common/requirements.txt

      - run:
          name: venvactivate
          command: . ./root/bin/activate
      - run:
          name: echo
          command: echo $PYTHONPATH
      - run:
          name: run tests
          command: pytest ~/circleci-test/common/tests/

workflows:
  version: 2
  build_test:
    jobs:
      - setup
